# Generated by Django 4.1.3 on 2022-11-04 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avartar",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="user",
            name="currency",
            field=models.CharField(
                choices=[("won", "Korean Won"), ("usd", "Dollar")],
                default="",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="language",
            field=models.CharField(
                choices=[("kr", "KR"), ("en", "En"), ("es", "ES")],
                default="",
                max_length=2,
            ),
        ),
    ]
