# Generated by Django 4.1.3 on 2022-11-07 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("houses", "0003_house_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="house",
            name="category",
        ),
    ]
