# Generated by Django 4.1.3 on 2022-11-09 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("houses", "0004_remove_house_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="houses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
