# Generated by Django 4.1.3 on 2022-11-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0004_room_category"),
        ("experiences", "0002_experience_category_alter_perk_detail_and_more"),
        ("wishlists", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wishlist",
            name="experience",
            field=models.ManyToManyField(blank=True, to="experiences.experience"),
        ),
        migrations.AlterField(
            model_name="wishlist",
            name="room",
            field=models.ManyToManyField(blank=True, to="rooms.room"),
        ),
    ]
